# main.config.yaml
environment:
  linux:
    path: "/path/to/GEOSDAS/bin"
    load_these_libraries:
      # You can trigger your g5_modules loads here
      - "g5_modules" 

tasks:
  cpcu:
    script_path: "/path/to/GEOSDAS/bin"
    script_name: "CPCU_B_Correct.x"
    args_to_pass:
      - "$M2PCORR_CPCU_RC"
      - "{DATE}"  # The Python wrapper will swap this for the cycle point
      - "{DATE}"
      
  cmap:
    script_path: "/path/to/GEOSDAS/bin"
    script_name: "CMAP_A_Correct.x"
    args_to_pass:
      - "$M2PCORR_CMAP_RC"
      - "{DATE}"
      - "{DATE}"
      
  merge:
    script_path: "/path/to/GEOSDAS/bin"
    script_name: "merge_Correct.x"
    args_to_pass:
      - "$M2PCORR_MRGE_RC"
      - "{DATE}"
      - "{DATE}"
